name: Swati Gupta
title: Swati Gupta's Website
theme: jekyll-theme-cayman
disqus: disqus_YVOuNa8Mpc
blog: https://swatigupta1997.github.io/blog_home/
homepage: https://swatigupta1997.github.io/
archive: https://swatigupta1997.github.io/
repository: https://github.com/Swatigupta1997/
permalink: /blog/:year/:month/:day/:title/
footer-links:
  email: gupta.swati369@gmail.com
  github: Swatigupta1997
  linkedin: swati-gupta-7761b0bb/
  rss: RSS Feed
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
