name: Swati Gupta
theme: jekyll-theme-cayman
permalink: /:title/
permalink: /:categories/:title/
collections:
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
defaults:
- scope:
    path: _posts
    type: posts
